// Ported from the app's CreditsTest (descriptions + roles), with the web's extra "Film" group.
import { describe, expect, it } from 'vitest'
import { classifyRole, descriptionLyrics, mergeCredits, parseDescriptionCredits, type CreditEntry, type CreditGroup } from '../src/lib/credits'

const names = (c: CreditEntry[], g: CreditGroup) => c.filter((e) => e.group === g).map((e) => e.name)
const role = (c: CreditEntry[], n: string) => c.find((e) => e.name === n)?.role
const fact = (c: CreditEntry[], r: string) => c.find((e) => !e.person && e.role === r)?.name

describe('credit roles (CreditsTest)', () => {
  it('maps roles to groups', () => {
    const one = (r: string, lenient = false) => classifyRole(r, lenient).map((c) => [c.group, c.role])
    expect(one('Composer')).toEqual([['WRITTEN', 'Composer']])
    expect(one('Composer, Lyricist')).toEqual([['WRITTEN', 'Composer, Lyricist']])
    expect(one('Music Director')).toEqual([['WRITTEN', 'Music director']])
    expect(one('Lyrics')).toEqual([['WRITTEN', 'Lyricist']])
    expect(one('Studio  Personnel, Mixing  Engineer')).toEqual([['ENGINEERING', 'Mixing engineer']])
    expect(one('Mixed & Mastered')).toEqual([['ENGINEERING', 'Mixing engineer, Mastering engineer']])
    expect(one('Producer, Mixer')).toEqual([['PRODUCED', 'Producer'], ['ENGINEERING', 'Mixing engineer']])
    expect(one('Associated Performer, Vocals')).toEqual([['PERFORMED', 'Vocals']])
    expect(one('Background Vocal')).toEqual([['PERFORMED', 'Background vocal']])
    expect(one('Music Label')).toEqual([['RIGHTS', 'Label']])
    expect(one('Instagram')).toEqual([])
    expect(one('Lyric Video')).toEqual([])
    expect(one('Theremin', true)).toEqual([['PERFORMED', 'Theremin']])
    expect(one('Theremin')).toEqual([])
    // Web: film credits get their own group instead of being dropped.
    expect(one('Director')).toEqual([['FILM', 'Director']])
    expect(one('Starring')).toEqual([['FILM', 'Cast']])
  })
})

describe('description credits (CreditsTest)', () => {
  const topic = `Provided to YouTube by Universal Music Group

Get Lucky · Daft Punk · Pharrell Williams · Nile Rodgers

Random Access Memories

℗ 2013 Daft Life Limited under exclusive license to Columbia Records

Released on: 2013-05-17

Producer: Thomas Bangalter
Producer: Guy-Manuel de Homem-Christo
Studio  Personnel, Mixing  Engineer: Mick Guzauski
Associated  Performer, Guitar: Nile Rodgers
Composer  Lyricist: Pharrell Williams
Composer, Lyricist: Thomas Bangalter
Music  Publisher: Imagem Music
Auto-generated by YouTube.`

  it('reads a Topic description', () => {
    const c = parseDescriptionCredits(topic)
    expect(names(c, 'PERFORMED')).toEqual(['Daft Punk', 'Pharrell Williams', 'Nile Rodgers'])
    expect(role(c, 'Daft Punk')).toBe('Artist')
    expect(role(c, 'Nile Rodgers')).toBe('Featured artist, Guitar')
    expect(names(c, 'WRITTEN')).toEqual(['Pharrell Williams', 'Thomas Bangalter'])
    expect(names(c, 'PRODUCED')).toEqual(['Thomas Bangalter', 'Guy-Manuel de Homem-Christo'])
    expect(names(c, 'ENGINEERING')).toEqual(['Mick Guzauski'])
    expect(names(c, 'RIGHTS')).toEqual(['Universal Music Group', 'Imagem Music', '℗ 2013 Daft Life Limited under exclusive license to Columbia Records'])
    expect(fact(c, 'Album')).toBe('Random Access Memories')
    expect(fact(c, 'Released')).toBe('2013-05-17')
  })

  it('keeps music roles from a free-form label description, and film credits in their own group', () => {
    const d = `Watch the official video of Kesariya!
Subscribe: https://youtube.com/x
Instagram: @someone

Song: Kesariya
♪ Singer: Arijit Singh
Music: Pritam
Lyrics: Amitabh Bhattacharya
Mixed & Mastered by: Eric Pillai
Music Label: Sony Music India
Director: Ayan Mukerji
Cast: Ranbir Kapoor, Alia Bhatt
Choreographer - Bosco Martis
0:00 Intro
1:30 Chorus
© 2022 Sony Music Entertainment India Pvt. Ltd.`
    const c = parseDescriptionCredits(d)
    expect(names(c, 'PERFORMED')).toEqual(['Arijit Singh'])
    expect(role(c, 'Arijit Singh')).toBe('Vocals')
    expect(names(c, 'WRITTEN')).toEqual(['Pritam', 'Amitabh Bhattacharya'])
    expect(role(c, 'Pritam')).toBe('Composer')
    expect(names(c, 'ENGINEERING')).toEqual(['Eric Pillai'])
    expect(names(c, 'RIGHTS')).toEqual(['Sony Music India', '© 2022 Sony Music Entertainment India Pvt. Ltd.'])
    expect(names(c, 'FILM')).toEqual(['Ayan Mukerji', 'Ranbir Kapoor', 'Alia Bhatt', 'Bosco Martis'])
    expect(role(c, 'Ranbir Kapoor')).toBe('Cast')
    expect(c.some((e) => e.name.includes('@') || e.name.includes('Kesariya'))).toBe(false)
  })

  it('splits free-form names and understands "by" lines', () => {
    const c = parseDescriptionCredits('Singers: A One, B Two & C Three\nMusic by D Four\nProduced by: E Five and F Six')
    expect(names(c, 'PERFORMED')).toEqual(['A One', 'B Two', 'C Three'])
    expect(names(c, 'WRITTEN')).toEqual(['D Four'])
    expect(names(c, 'PRODUCED')).toEqual(['E Five', 'F Six'])
  })

  it('ignores credit-less descriptions and merges sources', () => {
    expect(parseDescriptionCredits('')).toEqual([])
    expect(parseDescriptionCredits('Thanks for watching!\nLike and subscribe.\nhttps://x.y')).toEqual([])
    const m = mergeCredits([{ group: 'WRITTEN', role: 'Composer', name: 'Ann', person: true }], [{ group: 'WRITTEN', role: 'Lyricist', name: 'ann', person: true }, { group: 'RIGHTS', role: 'Label', name: 'L', person: false }])
    expect(m.length).toBe(2)
    expect(m[0].role).toBe('Composer, Lyricist')
  })
})

describe('label descriptions (web)', () => {
  const d = `Music - Pritam
Lyrics - Amitabh Bhattacharya
Vocal Conductors - Dev Arijit, Tushar Joshi
Directed by Ayan Mukerji
Starring Amitabh Bachchan, Ranbir Kapoor and Alia Bhatt

Lyrics:

MUKHDA
Mujhko itna bataaye koi
Kaise tujh se dil na lagaaye koi

[ Kesariya tera ishq hai piya
Rang jaaun jo main] x2

ANTARA
Patjhad ke mausam mein bhi

Label: Sony Music India`
  it('reads film credits written without colons', () => {
    const c = parseDescriptionCredits(d)
    expect(names(c, 'FILM')).toEqual(['Ayan Mukerji', 'Amitabh Bachchan', 'Ranbir Kapoor', 'Alia Bhatt'])
    expect(role(c, 'Dev Arijit')).toBe('Vocal conductor')
    expect(role(c, 'Amitabh Bhattacharya')).toBe('Lyricist')
  })
  it('extracts the lyrics typed into the description', () => {
    expect(descriptionLyrics(d)).toBe(`Mujhko itna bataaye koi
Kaise tujh se dil na lagaaye koi

Kesariya tera ishq hai piya
Rang jaaun jo main

Patjhad ke mausam mein bhi`)
    expect(descriptionLyrics(`Music: X
Lyrics: Y`)).toBeNull()
  })
})
